version: 1.0.1.4.{build}
image: Visual Studio 2015


environment:
  matrix:
    - PlatformToolset: v140_xp

platform:
    - x64
    - x86

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x86" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%

build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"\projects\msvc2015
    - msbuild nppcrypt.sln /m /p:configuration="%configuration%" /p:platform="%platform%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "build\$env:PLATFORM\nppcrypt.dll" -FileName nppcrypt.dll
        }

        if ($env:PLATFORM -eq "x86" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "build\$env:PLATFORM\nppcrypt.dll" -FileName nppcrypt.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v140_xp") {
            if($env:PLATFORM -eq "x64"){
            $ZipFileName = "nppcrypt_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
            7z a $ZipFileName build\$env:PLATFORM\nppcrypt.dll
            }
            if($env:PLATFORM -eq "x86"){
            $ZipFileName = "nppcrypt_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
            7z a $ZipFileName build\$env:PLATFORM\nppcrypt.dll
            }
        }
 
artifacts:
  - path: nppcrypt_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v140_xp
        configuration: Release
